#!/usr/bin/env python3
"""
Latticefall backlog.

The backlog lives in `backlog.json` (machine-owned, stable IDs) and is rendered to
`docs/BACKLOG.md` (human-owned, git-diffable, greppable). Never hand-edit the Markdown —
it is regenerated. Edit through this tool so IDs stay stable and nothing silently
disappears in a merge.

Why a script instead of a Markdown checklist: a checklist rots. Items lose their area,
their reason, and their link to the decision that caused them. Stable IDs mean a commit
can say "closes LF-014" and that reference survives reordering.

Usage:
    tools/backlog.py add "emissive bloom unwired" --kind bug --area art --pri high
    tools/backlog.py list --area audio --status open
    tools/backlog.py start LF-003
    tools/backlog.py done LF-003 --note "fixed in e7e775d"
    tools/backlog.py drop LF-009 --note "obsoleted by 007"
    tools/backlog.py render
"""

from __future__ import annotations

import argparse
import json
import subprocess
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STORE = ROOT / "backlog.json"
DOC = ROOT / "docs" / "BACKLOG.md"

KINDS = ["bug", "feature", "chore", "risk", "question", "polish"]
AREAS = ["art", "audio", "engine", "data", "design", "story", "tooling", "build", "meta"]
PRIS = ["blocker", "high", "med", "low"]
STATUSES = ["open", "wip", "done", "dropped"]

STATUS_MARK = {"open": " ", "wip": "~", "done": "x", "dropped": "-"}
PRI_ORDER = {p: i for i, p in enumerate(PRIS)}


def load() -> dict:
    if not STORE.exists():
        return {"next_id": 1, "items": []}
    return json.loads(STORE.read_text())


def save(db: dict) -> None:
    STORE.write_text(json.dumps(db, indent=2) + "\n")
    render(db)


def find(db: dict, ident: str) -> dict:
    ident = ident.upper()
    if not ident.startswith("LF-"):
        ident = f"LF-{int(ident):03d}"
    for it in db["items"]:
        if it["id"] == ident:
            return it
    raise SystemExit(f"no such item: {ident}")


def git_sha() -> str:
    r = subprocess.run(["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
                       capture_output=True, text=True)
    return r.stdout.strip() if r.returncode == 0 else "?"


# ────────────────────────────────────────────────────────────── commands ──

def cmd_add(args) -> int:
    db = load()
    item = {
        "id": f"LF-{db['next_id']:03d}",
        "title": args.title.strip(),
        "kind": args.kind,
        "area": args.area,
        "pri": args.pri,
        "status": "open",
        "why": (args.why or "").strip(),
        "opened": date.today().isoformat(),
        "closed": None,
        "note": "",
    }
    db["next_id"] += 1
    db["items"].append(item)
    save(db)
    print(f"{item['id']}  {item['title']}")
    return 0


def cmd_list(args) -> int:
    db = load()
    items = db["items"]
    if args.area:
        items = [i for i in items if i["area"] == args.area]
    if args.kind:
        items = [i for i in items if i["kind"] == args.kind]
    if args.status:
        items = [i for i in items if i["status"] == args.status]
    elif not args.all:
        items = [i for i in items if i["status"] in ("open", "wip")]
    items.sort(key=lambda i: (PRI_ORDER[i["pri"]], i["id"]))
    if not items:
        print("nothing matches")
        return 0
    for i in items:
        print(f"[{STATUS_MARK[i['status']]}] {i['id']}  {i['pri']:<7s} {i['area']:<8s} "
              f"{i['kind']:<8s} {i['title']}")
    print(f"\n{len(items)} item(s)")
    return 0


def _transition(args, status: str) -> int:
    db = load()
    it = find(db, args.id)
    it["status"] = status
    if args.note:
        it["note"] = args.note.strip()
    if status in ("done", "dropped"):
        it["closed"] = date.today().isoformat()
        if status == "done" and not it["note"]:
            it["note"] = f"closed at {git_sha()}"
    else:
        it["closed"] = None
    save(db)
    print(f"{it['id']} -> {status}")
    return 0


def render(db: dict | None = None) -> int:
    db = db or load()
    items = db["items"]
    open_items = [i for i in items if i["status"] in ("open", "wip")]
    closed = [i for i in items if i["status"] in ("done", "dropped")]
    open_items.sort(key=lambda i: (PRI_ORDER[i["pri"]], i["id"]))
    closed.sort(key=lambda i: i["id"], reverse=True)

    L = ["# Backlog", "",
         "*Generated by `tools/backlog.py`. Do not hand-edit — regenerate it.*", "",
         f"{len(open_items)} open · {len(closed)} closed", ""]

    if open_items:
        for pri in PRIS:
            group = [i for i in open_items if i["pri"] == pri]
            if not group:
                continue
            L += [f"## {pri}", "",
                  "| | ID | Area | Kind | Item |", "|---|---|---|---|---|"]
            for i in group:
                title = i["title"]
                if i["why"]:
                    title += f"<br><sub>{i['why']}</sub>"
                L.append(f"| `{STATUS_MARK[i['status']]}` | {i['id']} | {i['area']} | "
                         f"{i['kind']} | {title} |")
            L.append("")
    else:
        L += ["Nothing open.", ""]

    if closed:
        L += ["---", "", "## Closed", "",
              "| ID | Area | Item | Outcome |", "|---|---|---|---|"]
        for i in closed:
            L.append(f"| {i['id']} | {i['area']} | {i['title']} | "
                     f"{i['status']} — {i['note'] or '—'} |")
        L.append("")

    DOC.parent.mkdir(parents=True, exist_ok=True)
    DOC.write_text("\n".join(L))
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Latticefall backlog.")
    sub = ap.add_subparsers(dest="cmd", required=True)

    a = sub.add_parser("add", help="add an item")
    a.add_argument("title")
    a.add_argument("--kind", choices=KINDS, default="chore")
    a.add_argument("--area", choices=AREAS, default="meta")
    a.add_argument("--pri", choices=PRIS, default="med")
    a.add_argument("--why", help="one line: why this matters")
    a.set_defaults(fn=cmd_add)

    l = sub.add_parser("list", help="list items")
    l.add_argument("--area", choices=AREAS)
    l.add_argument("--kind", choices=KINDS)
    l.add_argument("--status", choices=STATUSES)
    l.add_argument("--all", action="store_true")
    l.set_defaults(fn=cmd_list)

    for name, status in [("start", "wip"), ("done", "done"), ("drop", "dropped"),
                         ("reopen", "open")]:
        p = sub.add_parser(name, help=f"mark an item {status}")
        p.add_argument("id")
        p.add_argument("--note")
        p.set_defaults(fn=lambda args, s=status: _transition(args, s))

    r = sub.add_parser("render", help="regenerate docs/BACKLOG.md")
    r.set_defaults(fn=lambda args: render())

    args = ap.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    raise SystemExit(main())
