#!/usr/bin/env python3
"""
Regenerate the factual half of docs/STATE.md.

Long sessions get summarized and context is lost. STATE.md is what survives — but a
hand-written status block rots the moment anything changes, and a stale handoff is
worse than none. So the *facts* are generated from the repo (gate results, backlog
counts, anchor grades, content inventory, recent commits) and only the *narrative*
stays hand-written.

Everything between the AUTO markers is owned by this script. Everything outside is
owned by whoever is working.

    .venv/bin/python tools/session.py            # rewrite the block in STATE.md
    .venv/bin/python tools/session.py --print    # just show it
    .venv/bin/python tools/session.py --no-window            # skip the windowed checks
    .venv/bin/python tools/session.py --gate-from gate.txt   # reuse the wrap's gate run
    .venv/bin/python tools/session.py --tier 2   # regenerate against a tier-2 gate (LF-115)

LF-115, fixed: this used to call `tools/check.py` with no `--tier` at all, which meant a
regeneration always ran (or re-read) the full tier-4 gate regardless of what the caller
asked for — harmless while every wrap ran tier 4 unconditionally, but PRC-20 makes the wrap
default to tier 2, and a STATE block silently produced from a tier-2 run while looking
identical to a tier-4 one would be exactly the "green partial run that reads like a full
one" CLAUDE.md calls out as the failure the whole gate contract exists to prevent. `--tier`
is now forwarded to the `check.py` subprocess (or recorded from a `--gate-from` artefact's
own `"tier"` field), and no extra bookkeeping was needed to *show* it: `check.py`'s own
summary line already reads `"tier N — ... passed ..."`, and that line is what lands
verbatim in STATE's Gate section — so a tier-2 regeneration says "tier 2" in the block
itself rather than silently claiming a full run.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATE = ROOT / "docs" / "STATE.md"
BEGIN = "<!-- BEGIN AUTO — generated by tools/session.py, do not hand-edit -->"
END = "<!-- END AUTO -->"


def sh(*args: str) -> str:
    r = subprocess.run(args, capture_output=True, text=True, cwd=str(ROOT))
    return r.stdout.strip()


def _parse_gate(out: str) -> tuple[str, list[str]]:
    lines = [l for l in out.splitlines() if l.startswith("[")]
    summary = next((l for l in out.splitlines() if "passed" in l), "unknown")
    return summary, lines


def _render_gate_json(doc: dict) -> tuple[str, list[str]]:
    """The same (summary, per-check lines) shape `_parse_gate` scrapes from human text, but
    built from a `tools/check.py --json` document instead — see PRC-03. Structured data
    means the block does not need `_parse_gate`'s caveats: real per-check `ms`, a real
    `status`, and the check's *full* detail rather than whatever line happened to start with
    `[`.
    """
    mark = {"ok": "  ok  ", "FAIL": " FAIL ", "skip": " skip "}
    lines = []
    for c in doc.get("checks", []):
        detail_lines = (c.get("detail") or "").splitlines()
        first = detail_lines[0] if detail_lines else ""
        lines.append(f"[{mark.get(c['status'], c['status'])}] {c['name']:<20s} "
                     f"{c['ms']:6.0f}ms  {first}")
        if c["status"] == "FAIL":
            lines += [f"           {l}" for l in detail_lines[1:]]
    summary = doc.get("summary", {}).get("text") or "unknown"
    return summary, lines


def gate(no_window: bool = False, gate_from: Path | None = None,
        tier: int | None = None) -> tuple[str, list[str]]:
    """The gate's per-check lines for the STATE block, run now or read from a saved run.

    `gate_from` exists because the wrap procedure runs the gate and *then* runs this script,
    which re-ran the whole gate to build the block — paying for the eleven-minute parity
    check twice per wrap, and opening the rendered checks' Godot windows twice. Save the
    gate's output and hand it over instead. Pipe it through `python -u`, or the block
    buffering on a redirected stdout means the file is empty until the run ends.

    `gate_from` may point at either a `tools/check.py --json` artefact or the older saved
    stdout of a plain run — JSON is tried first and preferred when it parses as this file's
    schema. The old text-scrape path is a *loose* read of whatever line happened to start
    with `[`, which is why its result carried the "(from gate.txt, not re-run)" hedge; the
    JSON path is the run's own structured record, so nothing is being hedged and the caveat
    is dropped. The text path remains for any artefact saved before this existed.

    `no_window` forwards `--no-window`, which is not cosmetic: three checks open a real
    Godot window on whoever's desktop this runs on, and macOS stalls a window it thinks is
    occluded — so regenerating STATE while somebody is using the machine both interrupts
    them and can wedge for half an hour (decision 051, LF-061). Either way the skipped lines
    stay in the block as `skip`, so the record says what did not run rather than implying
    18 green.

    `tier` forwards `--tier` to the subprocess (LF-115, fixed by PRC-20). Before this, a
    STATE regeneration always ran (or trusted) a full tier-4 gate no matter what the caller
    asked for — harmless while every wrap ran tier 4 unconditionally, but PRC-20 makes the
    wrap default to tier 2, and this script is what writes the "Gate" section a reader
    trusts. `None` (the default) omits `--tier` entirely, which is `check.py`'s own tier-4
    default — unchanged behaviour for every existing caller. No separate bookkeeping was
    needed to make the *result* honest about which tier ran: `check.py`'s own summary line
    already reads `"tier N — X passed · Y failed · Z skipped · Wms"`, and that exact line is
    what `_parse_gate`/`_render_gate_json` both return as `summary` — so whichever tier
    actually ran says so in the block itself, on a `--gate-from` read as much as a live run
    (a saved JSON artefact carries its own `"tier"` key, which is what `check.py --json`
    always records regardless of how it was invoked).
    """
    if gate_from is not None:
        text = gate_from.read_text()
        doc = None
        try:
            doc = json.loads(text)
        except json.JSONDecodeError:
            doc = None
        if isinstance(doc, dict) and doc.get("schema") == "latticefall-gate":
            return _render_gate_json(doc)
        summary, lines = _parse_gate(text)
        return summary + f"   (from {gate_from.name}, not re-run)", lines

    cmd = [sys.executable, "-u", str(ROOT / "tools" / "check.py")]
    if no_window:
        cmd.append("--no-window")
    if tier is not None:
        cmd += ["--tier", str(tier)]
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=str(ROOT))
    summary, lines = _parse_gate(r.stdout)
    if no_window:
        summary += "   (--no-window: the three rendered checks did not run)"
    return summary, lines


def backlog() -> dict:
    p = ROOT / "backlog.json"
    if not p.exists():
        return {}
    items = json.loads(p.read_text())["items"]
    openish = [i for i in items if i["status"] in ("open", "wip")]
    by_pri: dict[str, list[str]] = {}
    for i in sorted(openish, key=lambda i: i["id"]):
        by_pri.setdefault(i["pri"], []).append(f"{i['id']} {i['title']}")
    return {"open": len(openish), "closed": len(items) - len(openish), "by_pri": by_pri}


def anchors() -> list[dict]:
    ## `--jobs 0` is one worker per core. The sim has no RNG and no shared state, so the
    ## parallel run returns the same cells in the same order (CLAUDE.md) — grading 24 anchors
    ## serially here was costing about three and a half minutes of every wrap for nothing.
    r = subprocess.run([sys.executable, str(ROOT / "sim" / "run.py"), "--json", "--jobs", "0"],
                       capture_output=True, text=True, cwd=str(ROOT))
    try:
        return json.loads(r.stdout)
    except Exception:
        return []


def inventory() -> dict:
    def n(pattern: str, base: Path) -> int:
        return len(list(base.glob(pattern))) if base.exists() else 0
    a = ROOT / "assets" / "audio"
    return {
        "anchors": n("anchor-*.json", ROOT / "data" / "anchors"),
        "dialog": n("anchor-*.json", ROOT / "data" / "dialog"),
        "sfx": n("*.wav", a / "sfx"),
        "music": n("*.ogg", a / "music"),
        "renders": n("**/*.png", ROOT / "assets" / "renders"),
        "gd_scripts": len(list((ROOT / "scripts").rglob("*.gd"))) if (ROOT / "scripts").exists() else 0,
        "scenes": len(list((ROOT / "scenes").rglob("*.tscn"))) if (ROOT / "scenes").exists() else 0,
    }


def build(no_window: bool = False, gate_from: Path | None = None,
         tier: int | None = None) -> str:
    summary, lines = gate(no_window, gate_from, tier)
    bl = backlog()
    inv = inventory()
    ancs = anchors()

    L = [BEGIN, "",
         f"*Facts below regenerated {date.today().isoformat()}. "
         f"Run `.venv/bin/python tools/session.py` after any change.*", "",
         "### Gate", "", "```"]
    L += lines + ["", summary, "```", ""]

    L += ["### Inventory", "",
          "| | count |", "|---|---|",
          f"| anchors authored | {inv['anchors']} of 24 |",
          f"| dialog files | {inv['dialog']} |",
          f"| sfx | {inv['sfx']} of ~60 |",
          f"| music tracks | {inv['music']} of 14 |",
          f"| sprite renders | {inv['renders']} |",
          f"| godot scripts | {inv['gd_scripts']} |",
          f"| godot scenes | {inv['scenes']} |", ""]

    if ancs:
        L += ["### Anchor grades", "",
              "| anchor | act | cap | waves | standard | hard | brutal | verdict |",
              "|---|---|---|---|---|---|---|---|"]
        for a in ancs:
            cells = []
            for d in ("standard", "hard", "brutal"):
                x = a["by_difficulty"].get(d)
                cells.append(f"{x['distinct_winning_builds']}/{x['distinct_builds_tried']}"
                             if x else "—")
            verdict = "ok" if a["ok"] else "; ".join(a["problems"])[:60]
            L.append(f"| {a['anchor']} | {a['act']} | {a['capacity_mw']:.0f} MW | "
                     f"{a['waves']} | {cells[0]} | {cells[1]} | {cells[2]} | {verdict} |")
        L += ["", "*Cells are distinct winning builds / distinct builds tried.*", ""]

    if bl:
        L += ["### Backlog", "", f"{bl['open']} open · {bl['closed']} closed", ""]
        for pri in ("blocker", "high", "med", "low"):
            for line in bl["by_pri"].get(pri, []):
                L.append(f"- `{pri}` {line}")
        L.append("")

    L += ["### Recent commits", "", "```"]
    L += sh("git", "log", "--oneline", "-8").splitlines()
    L += ["```", "", END]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate the auto block in STATE.md.")
    ap.add_argument("--print", action="store_true", dest="show")
    ap.add_argument("--gate-from", type=Path, metavar="FILE",
                    help="read a saved gate run instead of re-running it. The wrap runs the "
                         "gate already; without this the block costs a second parity run. "
                         "Accepts a tools/check.py --json artefact (preferred: structured, "
                         "no hedging in the block) or the older saved stdout of a plain run.")
    ap.add_argument("--no-window", action="store_true",
                    help="forward --no-window to the gate: skip the three checks that\nopen a real Godot window. Use when somebody is working on this machine.")
    ap.add_argument("--tier", type=int, choices=(1, 2, 3, 4), default=None,
                    help="forward --tier to the gate (LF-115, PRC-20). Omit to keep the old "
                         "behaviour: check.py's own tier-4 default. A --gate-from artefact "
                         "carries its own tier already and ignores this flag — pass --tier "
                         "only when this script is running the gate itself.")
    args = ap.parse_args()

    block = build(args.no_window, args.gate_from, args.tier)
    if args.show:
        print(block)
        return 0

    text = STATE.read_text() if STATE.exists() else "# State\n\n"
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        text = head + block + tail
    else:
        text = text.rstrip() + "\n\n---\n\n" + block + "\n"
    STATE.write_text(text)
    print(f"updated {STATE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
