#!/usr/bin/env python3
"""
Regenerate the factual half of docs/STATE.md.

Long sessions get summarized and context is lost. STATE.md is what survives — but a
hand-written status block rots the moment anything changes, and a stale handoff is
worse than none. So the *facts* are generated from the repo (gate results, backlog
counts, anchor grades, content inventory, recent commits) and only the *narrative*
stays hand-written.

Everything between the AUTO markers is owned by this script. Everything outside is
owned by whoever is working.

    .venv/bin/python tools/session.py            # rewrite the block in STATE.md
    .venv/bin/python tools/session.py --print    # just show it
    .venv/bin/python tools/session.py --no-window            # skip the windowed checks
    .venv/bin/python tools/session.py --gate-from gate.txt   # reuse the wrap's gate run
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STATE = ROOT / "docs" / "STATE.md"
BEGIN = "<!-- BEGIN AUTO — generated by tools/session.py, do not hand-edit -->"
END = "<!-- END AUTO -->"


def sh(*args: str) -> str:
    r = subprocess.run(args, capture_output=True, text=True, cwd=str(ROOT))
    return r.stdout.strip()


def _parse_gate(out: str) -> tuple[str, list[str]]:
    lines = [l for l in out.splitlines() if l.startswith("[")]
    summary = next((l for l in out.splitlines() if "passed" in l), "unknown")
    return summary, lines


def gate(no_window: bool = False, gate_from: Path | None = None) -> tuple[str, list[str]]:
    """The gate's per-check lines for the STATE block, run now or read from a saved run.

    `gate_from` exists because the wrap procedure runs the gate and *then* runs this script,
    which re-ran the whole gate to build the block — paying for the eleven-minute parity
    check twice per wrap, and opening the rendered checks' Godot windows twice. Save the
    gate's output and hand it over instead. Pipe it through `python -u`, or the block
    buffering on a redirected stdout means the file is empty until the run ends.

    `no_window` forwards `--no-window`, which is not cosmetic: three checks open a real
    Godot window on whoever's desktop this runs on, and macOS stalls a window it thinks is
    occluded — so regenerating STATE while somebody is using the machine both interrupts
    them and can wedge for half an hour (decision 051, LF-061). Either way the skipped lines
    stay in the block as `skip`, so the record says what did not run rather than implying
    18 green.
    """
    if gate_from is not None:
        out = gate_from.read_text()
        summary, lines = _parse_gate(out)
        return summary + f"   (from {gate_from.name}, not re-run)", lines

    cmd = [sys.executable, "-u", str(ROOT / "tools" / "check.py")]
    if no_window:
        cmd.append("--no-window")
    r = subprocess.run(cmd, capture_output=True, text=True, cwd=str(ROOT))
    summary, lines = _parse_gate(r.stdout)
    if no_window:
        summary += "   (--no-window: the three rendered checks did not run)"
    return summary, lines


def backlog() -> dict:
    p = ROOT / "backlog.json"
    if not p.exists():
        return {}
    items = json.loads(p.read_text())["items"]
    openish = [i for i in items if i["status"] in ("open", "wip")]
    by_pri: dict[str, list[str]] = {}
    for i in sorted(openish, key=lambda i: i["id"]):
        by_pri.setdefault(i["pri"], []).append(f"{i['id']} {i['title']}")
    return {"open": len(openish), "closed": len(items) - len(openish), "by_pri": by_pri}


def anchors() -> list[dict]:
    ## `--jobs 0` is one worker per core. The sim has no RNG and no shared state, so the
    ## parallel run returns the same cells in the same order (CLAUDE.md) — grading 24 anchors
    ## serially here was costing about three and a half minutes of every wrap for nothing.
    r = subprocess.run([sys.executable, str(ROOT / "sim" / "run.py"), "--json", "--jobs", "0"],
                       capture_output=True, text=True, cwd=str(ROOT))
    try:
        return json.loads(r.stdout)
    except Exception:
        return []


def inventory() -> dict:
    def n(pattern: str, base: Path) -> int:
        return len(list(base.glob(pattern))) if base.exists() else 0
    a = ROOT / "assets" / "audio"
    return {
        "anchors": n("anchor-*.json", ROOT / "data" / "anchors"),
        "dialog": n("anchor-*.json", ROOT / "data" / "dialog"),
        "sfx": n("*.wav", a / "sfx"),
        "music": n("*.ogg", a / "music"),
        "renders": n("**/*.png", ROOT / "assets" / "renders"),
        "gd_scripts": len(list((ROOT / "scripts").rglob("*.gd"))) if (ROOT / "scripts").exists() else 0,
        "scenes": len(list((ROOT / "scenes").rglob("*.tscn"))) if (ROOT / "scenes").exists() else 0,
    }


def build(no_window: bool = False, gate_from: Path | None = None) -> str:
    summary, lines = gate(no_window, gate_from)
    bl = backlog()
    inv = inventory()
    ancs = anchors()

    L = [BEGIN, "",
         f"*Facts below regenerated {date.today().isoformat()}. "
         f"Run `.venv/bin/python tools/session.py` after any change.*", "",
         "### Gate", "", "```"]
    L += lines + ["", summary, "```", ""]

    L += ["### Inventory", "",
          "| | count |", "|---|---|",
          f"| anchors authored | {inv['anchors']} of 24 |",
          f"| dialog files | {inv['dialog']} |",
          f"| sfx | {inv['sfx']} of ~60 |",
          f"| music tracks | {inv['music']} of 14 |",
          f"| sprite renders | {inv['renders']} |",
          f"| godot scripts | {inv['gd_scripts']} |",
          f"| godot scenes | {inv['scenes']} |", ""]

    if ancs:
        L += ["### Anchor grades", "",
              "| anchor | act | cap | waves | standard | hard | brutal | verdict |",
              "|---|---|---|---|---|---|---|---|"]
        for a in ancs:
            cells = []
            for d in ("standard", "hard", "brutal"):
                x = a["by_difficulty"].get(d)
                cells.append(f"{x['distinct_winning_builds']}/{x['distinct_builds_tried']}"
                             if x else "—")
            verdict = "ok" if a["ok"] else "; ".join(a["problems"])[:60]
            L.append(f"| {a['anchor']} | {a['act']} | {a['capacity_mw']:.0f} MW | "
                     f"{a['waves']} | {cells[0]} | {cells[1]} | {cells[2]} | {verdict} |")
        L += ["", "*Cells are distinct winning builds / distinct builds tried.*", ""]

    if bl:
        L += ["### Backlog", "", f"{bl['open']} open · {bl['closed']} closed", ""]
        for pri in ("blocker", "high", "med", "low"):
            for line in bl["by_pri"].get(pri, []):
                L.append(f"- `{pri}` {line}")
        L.append("")

    L += ["### Recent commits", "", "```"]
    L += sh("git", "log", "--oneline", "-8").splitlines()
    L += ["```", "", END]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description="Regenerate the auto block in STATE.md.")
    ap.add_argument("--print", action="store_true", dest="show")
    ap.add_argument("--gate-from", type=Path, metavar="FILE",
                    help="read a saved gate run instead of re-running it. The wrap runs the "
                         "gate already; without this the block costs a second parity run.")
    ap.add_argument("--no-window", action="store_true",
                    help="forward --no-window to the gate: skip the three checks that\nopen a real Godot window. Use when somebody is working on this machine.")
    args = ap.parse_args()

    block = build(args.no_window, args.gate_from)
    if args.show:
        print(block)
        return 0

    text = STATE.read_text() if STATE.exists() else "# State\n\n"
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
        text = head + block + tail
    else:
        text = text.rstrip() + "\n\n---\n\n" + block + "\n"
    STATE.write_text(text)
    print(f"updated {STATE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
